### PR TITLE
Add box-sizing of content-box to .add-on

### PR DESCRIPTION
**Pull request by kabeaty**
#### What's this PR do?
Add box-sizing of content-box to .add-on to fix box-sizing of border-box currently making buttons render not as intended.

#### Why are we doing this? How does it help us?
Gets us ready for Higher Ed Explorer pointer.

#### How should this be manually tested?
Run locally, inspect elements, and when you check out .add-on, you should see 'box-sizing: content-box' as a style for it. What I did was then go to http://www.texastribune.org/higher-ed/explore/, inspect elements there, insert 'box-sizing: content-box' to .add-on in dev tools, and visually confirm that adding this 'box-sizing: content-box' style fixes the buttons.

#### What are the relevant tickets?
Email ask from Rodney.

#### Next steps?
Get Chris to transfer over ownership of tx_highered on PyPi.
Bump version and run `make release` on master to push the new version to PyPi.

#### Technical debt note

### CODE REVIEW

**Comment by risatrix** [comment]
Worked for me, testing via the method suggested above.

**Comment by crccheck** [comment]
looks like the edit should go into `https://github.com/texastribune/the-dp/blob/master/tx_highered/static/tx_highered/vendor/bootstrap/scss/_forms.scss#L394`

and then rebuild using https://github.com/texastribune/the-dp/blob/master/tx_highered/static/tx_highered/vendor/bootstrap/build.sh

sorry, this pre-dates all the nicer build tools and better staticfiles layout

**OR**

add a hack to the bootstrap hacks section of https://github.com/texastribune/the-dp/blob/master/tx_highered/static/tx_highered/scss/tx_highered.scss#L190-L225 
and rebuild using https://github.com/texastribune/the-dp/blob/master/tx_highered/static/tx_highered/build.sh

----

editing the compiles css directly leaves you open to getting the change overwritten later.

**Comment by kabeaty** [comment]
Ah, I see how it's all working now, thanks! Updated, but now trying to look into why Sass updated the naming of colors when it compiled...

**Comment by crccheck** [comment]
it's not a big deal as long as nothing of substance changed, and looking at the diff, it doesn't look like anything did. Sass changes their style between versions. This is why the main Texas Tribune project has a gemfile that pins the version of sass.

**Comment by rdmurphy** [comment]
There's probably also an argument for not committing the compiled versions, but that's a bigger thing. The diff clashes that'll pop up there that don't matter can be really annoying.

**Comment by x110dc** [comment]
@rdmurphy I strongly favor that argument (don't commit compiled anythin) but it's not easy/straightforward to get there. It's on our (long) list though. :-)

**Comment by risatrix** [comment]
LGTM!

**Comment by risatrix** [comment]
Also, re: committing css I agree, but cf. rest of trib project to fix :/ Drink whenever you see committed compiled assets...

**Pull request merged**
